import jsPDF from "jspdf";
import { dialog } from "../dialogService";

export class IntegrationPdfGenerator {
  static generatePdf(integrationData, projectName = "Project", filename = null) {
    const testRuns = Array.isArray(integrationData?.test_runs)
      ? integrationData.test_runs
      : [];

    if (!testRuns.length) {
      alert("No integration test data available to generate PDF report");
      return;
    }

    try {
      const doc = new jsPDF("p", "mm", "a4");
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 18;
      const contentWidth = pageWidth - 2 * margin;
      const accentColor = { r: 20, g: 184, b: 166 };
      const accentSoft = { r: 45, g: 212, b: 191 };
      const neutralText = [55, 65, 81];
      const highlightText = [15, 118, 110];
      let y = 28;

      const formatDate = (value) => {
        if (!value) return "Not provided";
        try {
          const parsed = new Date(value);
          if (Number.isNaN(parsed.getTime())) {
            return String(value);
          }
          return parsed.toLocaleString();
        } catch (error) {
          return String(value);
        }
      };

      const truncate = (value, length = 220) => {
        if (typeof value !== "string") return value;
        if (value.length <= length) return value;
        return `${value.slice(0, length)}…`;
      };

      const checkPage = (extra = 40) => {
        if (y + extra > pageHeight - 18) {
          doc.addPage();
          drawPageDecorations();
          y = 32;
        }
      };

      const drawPageDecorations = () => {
        doc.setDrawColor(236, 239, 244);
        doc.setLineWidth(0.2);
        doc.line(margin, 20, pageWidth - margin, 20);
      };

      const sectionTitle = (title, subtitle = null) => {
        checkPage(subtitle ? 36 : 28);
        doc.setFontSize(13);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(accentColor.r, accentColor.g, accentColor.b);
        doc.text(title.toUpperCase(), margin, y);
        y += 7;

        if (subtitle) {
          doc.setFontSize(9);
          doc.setFont("helvetica", "normal");
          doc.setTextColor(100, 116, 139);
          const lines = doc.splitTextToSize(subtitle, contentWidth);
          doc.text(lines, margin, y);
          y += lines.length * 4.5 + 2;
        }

        doc.setDrawColor(accentSoft.r, accentSoft.g, accentSoft.b);
        doc.setLineWidth(0.6);
        doc.line(margin, y, margin + 35, y);
        doc.setDrawColor(228, 233, 243);
        doc.setLineWidth(0.2);
        doc.line(margin + 35, y, pageWidth - margin, y);
        y += 8;
      };

      const drawIntroParagraph = () => {
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...neutralText);
        const intro =
          "Integration coverage overview generated by the Testing Agent. Inspect cross-service scenarios, triggered flows, and observed execution metadata.";
        const lines = doc.splitTextToSize(intro, contentWidth);
        checkPage(lines.length * 5 + 12);
        doc.text(lines, margin, y);
        y += lines.length * 5 + 6;
      };

      const renderSummaryCards = (cards) => {
        const cardsPerRow = 2;
        const gap = 8;
        const cardWidth = (contentWidth - gap) / cardsPerRow;
        const cardHeight = 44;
        let columnIndex = 0;
        let rowTop = y;

        cards.forEach((card, index) => {
          if (columnIndex === 0) {
            checkPage(cardHeight + 14);
            rowTop = y;
          }

          const x = margin + columnIndex * (cardWidth + gap);
          doc.setFillColor(241, 253, 250);
          doc.roundedRect(x, rowTop, cardWidth, cardHeight, 4, 4, "F");
          doc.setDrawColor(209, 250, 229);
          doc.roundedRect(x, rowTop, cardWidth, cardHeight, 4, 4, "S");

          doc.setFillColor(accentSoft.r, accentSoft.g, accentSoft.b);
          doc.circle(x + 6, rowTop + 10, 2, "F");

          doc.setFont("helvetica", "bold");
          doc.setFontSize(8);
          doc.setTextColor(accentSoft.r, accentSoft.g, accentSoft.b);
          doc.text(card.label.toUpperCase(), x + 12, rowTop + 11);

          doc.setFontSize(13);
          doc.setTextColor(13, 148, 136);
          doc.text(String(card.value), x + 12, rowTop + 21);

          if (card.helper) {
            doc.setFont("helvetica", "normal");
            doc.setFontSize(8);
            doc.setTextColor(51, 65, 85);
            const helperLines = doc.splitTextToSize(card.helper, cardWidth - 24);
            doc.text(helperLines, x + 12, rowTop + 30);
          }

          columnIndex += 1;

          if (columnIndex === cardsPerRow || index === cards.length - 1) {
            y = rowTop + cardHeight + 8;
            columnIndex = 0;
          }
        });
      };

      const renderRunBlock = (run, idx) => {
        const runId = run?.doc_id || run?._id || `integration_${idx + 1}`;
        const paddingX = 12;
        const paddingY = 12;
        const innerWidth = contentWidth - paddingX * 2;
        const blockEntries = [];
        const resolveLineHeight = (size) => Math.max(4.2, size * 0.46);

        const createGroup = (text, options = {}) => {
          const {
            size = 9,
            bold = false,
            color = neutralText,
            indent = 0,
            spacing = 2,
          } = options;

          doc.setFont("helvetica", bold ? "bold" : "normal");
          doc.setFontSize(size);
          const availableWidth = innerWidth - indent;
          const lines = doc.splitTextToSize(String(text), availableWidth);
          const lineHeight = resolveLineHeight(size);
          const height = lines.length * lineHeight;
          return {
            lines,
            size,
            bold,
            color,
            indent,
            lineHeight,
            height,
            spacing,
          };
        };

        const pushIfContent = (text, options) => {
          if (!text) return;
          blockEntries.push(createGroup(text, options));
        };

        blockEntries.push(
          createGroup(`Integration Run #${idx + 1}`, {
            size: 12,
            bold: true,
            color: [13, 148, 136],
            spacing: 3.5,
          })
        );
        blockEntries.push(
          createGroup(`Identifier: ${runId}`, {
            size: 9,
            color: [75, 85, 99],
            spacing: 1.5,
          })
        );

        const timelineBits = [];
        timelineBits.push(`Created • ${formatDate(run?.created_at)}`);
        timelineBits.push(`Updated • ${formatDate(run?.updated_at)}`);
        if (run?.testrun_count !== undefined) {
          timelineBits.push(`Executions • ${run.testrun_count}`);
        }
        blockEntries.push(
          createGroup(timelineBits.join("    |    "), {
            size: 9,
            color: [45, 55, 72],
            spacing: 1.5,
          })
        );

        if (run?.owner) {
          pushIfContent(`Owner: ${run.owner}`, {
            size: 8.5,
            color: [15, 118, 110],
            spacing: 1.5,
          });
        }
        if (run?.environment) {
          pushIfContent(`Environment: ${run.environment}`, {
            size: 8.5,
            color: [45, 55, 72],
            spacing: 1.5,
          });
        }

        const scenarios = Array.isArray(run?.scenarios) ? run.scenarios : [];
        const totalScenarios = scenarios.length;
        const flowCount = scenarios.reduce(
          (sum, scenario) => sum + (Array.isArray(scenario?.flow_names) ? scenario.flow_names.length : 0),
          0
        );
        blockEntries.push(
          createGroup(`Scenarios ${totalScenarios}    •    Flows ${flowCount}`, {
            size: 9,
            color: highlightText,
            spacing: 2,
          })
        );

        if (run?.notes) {
          pushIfContent(truncate(run.notes, 260), {
            size: 8,
            color: [100, 116, 139],
            spacing: 2.5,
          });
        }

        if (scenarios.length) {
          blockEntries.push(
            createGroup("Scenario Highlights", {
              size: 9,
              bold: true,
              color: [30, 41, 59],
              spacing: 3,
            })
          );

          scenarios.slice(0, 5).forEach((scenario, index) => {
            const name = scenario?.scenario_name || scenario?.name || `Scenario ${index + 1}`;
            const status = scenario?.status || scenario?.result;
            const statusLabel = status ? `Status: ${status}` : null;
            const descriptor = [statusLabel, scenario?.last_run_id ? `Run ID: ${scenario.last_run_id}` : null]
              .filter(Boolean)
              .join(" · ");

            blockEntries.push(
              createGroup(`${index + 1}. ${name}`, {
                size: 9,
                color: [45, 55, 72],
                indent: 4,
                spacing: 1.5,
              })
            );

            if (descriptor) {
              blockEntries.push(
                createGroup(descriptor, {
                  size: 8,
                  color: [71, 85, 105],
                  indent: 8,
                  spacing: 1.5,
                })
              );
            }

            const flows = Array.isArray(scenario?.flow_names)
              ? scenario.flow_names.filter(Boolean)
              : [];
            if (flows.length) {
              blockEntries.push(
                createGroup(`Flows: ${flows.join(", ")}`, {
                  size: 8,
                  color: highlightText,
                  indent: 8,
                  spacing: 1.5,
                })
              );
            }

            if (scenario?.test_script) {
              blockEntries.push(
                createGroup(truncate(scenario.test_script, 280), {
                  size: 7.8,
                  color: [107, 114, 128],
                  indent: 8,
                  spacing: 1.5,
                })
              );
            }

            if (scenario?.report) {
              const reportPreview = truncate(
                typeof scenario.report === "string"
                  ? scenario.report
                  : JSON.stringify(scenario.report, null, 2),
                260
              );
              blockEntries.push(
                createGroup(`Report: ${reportPreview}`, {
                  size: 7.8,
                  color: [148, 163, 184],
                  indent: 8,
                  spacing: 2,
                })
              );
            }
          });

          if (scenarios.length > 5) {
            blockEntries.push(
              createGroup(
                `…plus ${scenarios.length - 5} additional scenario${
                  scenarios.length - 5 === 1 ? "" : "s"
                } tracked`,
                {
                  size: 8,
                  color: [148, 163, 184],
                  indent: 4,
                  spacing: 1.5,
                }
              )
            );
          }
        } else {
          blockEntries.push(
            createGroup("No scenarios were captured for this run.", {
              size: 8.5,
              color: [148, 163, 184],
              spacing: 1.5,
            })
          );
        }

        const totalContentHeight = blockEntries.reduce(
          (sum, entry) => sum + entry.height + entry.spacing,
          0
        ) - (blockEntries.length
          ? blockEntries[blockEntries.length - 1].spacing
          : 0);

        const blockHeight = paddingY * 2 + totalContentHeight;
        checkPage(blockHeight + 10);

        const blockTop = y;
        doc.setFillColor(250, 253, 252);
        doc.roundedRect(margin, blockTop, contentWidth, blockHeight, 6, 6, "F");
        doc.setDrawColor(210, 250, 230);
        doc.roundedRect(margin, blockTop, contentWidth, blockHeight, 6, 6, "S");
        doc.setFillColor(accentColor.r, accentColor.g, accentColor.b);
        doc.roundedRect(margin, blockTop, 4, blockHeight, 6, 0, "F");

        let cursorY = blockTop + paddingY + 4;
        blockEntries.forEach((entry, entryIndex) => {
          doc.setFont("helvetica", entry.bold ? "bold" : "normal");
          doc.setFontSize(entry.size);
          doc.setTextColor(...entry.color);

          const baseX = margin + paddingX + entry.indent;
          entry.lines.forEach((line) => {
            doc.text(line, baseX, cursorY);
            cursorY += entry.lineHeight;
          });

          if (entryIndex !== blockEntries.length - 1) {
            cursorY += entry.spacing;
          }
        });

        y = blockTop + blockHeight + 10;
      };

      const drawHeader = () => {
        doc.setFillColor(accentColor.r, accentColor.g, accentColor.b);
        doc.rect(0, 0, pageWidth, 46, "F");
        doc.setFillColor(15, 118, 110);
        doc.circle(pageWidth - 30, -12, 52, "F");
        doc.setFillColor(110, 231, 183);
        doc.circle(pageWidth - 68, 12, 34, "F");

        doc.setFont("helvetica", "bold");
        doc.setFontSize(21);
        doc.setTextColor(255, 255, 255);
        doc.text("Testing Agent", margin, 22);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        doc.text("Integration Testing Insights", margin, 32);

        doc.setFontSize(9);
        doc.text(`Project: ${projectName}`, pageWidth - margin - 66, 18);
        doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth - margin - 66, 26);

        drawPageDecorations();
        y = 56;
      };

      drawHeader();
      sectionTitle("Executive Summary", "Cross-service testing runs and scenario execution insights captured by the testing agent.");
      drawIntroParagraph();

      const totalRuns = integrationData?.total_test_runs || testRuns.length;
      const totalScenarios = integrationData?.total_scenarios || testRuns.reduce(
        (sum, run) => sum + (Array.isArray(run?.scenarios) ? run.scenarios.length : 0),
        0
      );
      const avgScenariosPerRun = totalRuns
        ? (totalScenarios / totalRuns).toFixed(1)
        : "0";
      const distinctServices = (() => {
        const services = new Set();
        testRuns.forEach((run) => {
          run?.scenarios?.forEach((scenario) => {
            if (Array.isArray(scenario?.flow_names)) {
              scenario.flow_names.forEach((flow) => services.add(flow));
            }
          });
        });
        return services.size;
      })();
      const lastRun = testRuns
        .map((run) => run?.updated_at || run?.created_at)
        .filter(Boolean)
        .map((value) => new Date(value))
        .filter((date) => !Number.isNaN(date.getTime()))
        .sort((a, b) => b.getTime() - a.getTime())[0];

      renderSummaryCards([
        {
          label: "Total Runs",
          value: totalRuns,
          helper: "Integration executions observed in this report.",
        },
        {
          label: "Total Scenarios",
          value: totalScenarios,
          helper: "Composed across all collected runs.",
        },
        {
          label: "Avg Scenarios / Run",
          value: avgScenariosPerRun,
          helper: `Distinct Flows referenced: ${distinctServices}`,
        },
        {
          label: "Most Recent Run",
          value: lastRun ? lastRun.toLocaleString() : "Timestamp unavailable",
          helper: "Pulled from run metadata (updated or created).",
        },
      ]);

      sectionTitle(
        "Run Breakdown",
        "Detailed review of each integration run with scenario highlights, flow coverage, and supporting evidence."
      );

      testRuns.forEach((run, idx) => {
        renderRunBlock(run, idx);
      });

      const totalPages = doc.internal.pages.length - 1;
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(120, 120, 120);
        doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, {
          align: "center",
        });
        doc.text("Generated by Testing Agent", margin, pageHeight - 10);
      }

      if (!filename) {
        const ts = new Date().toISOString().slice(0, 19).replace(/:/g, "-");
        filename = `integration_report_${ts}.pdf`;
      }

      doc.save(filename);
      console.log("✅ Integration PDF report generated successfully");
    } catch (err) {
      console.error("❌ Integration PDF generation failed:", err);
      dialog.alert({
        title: "Export failed",
        message: "Failed to generate Integration PDF report. Please try again.",
        variant: "danger",
      });
    }
  }
}

export default IntegrationPdfGenerator;

